export const USER_SIGTNIN_REQUEST = 'USER_SIGTNIN_REQUEST';
export const USER_SIGTNIN_SUCCESS = 'USER_SIGTNIN_SUCCESS';
export const USER_SIGTNIN_FAIL = 'USER_SIGTNIN_FAIL';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
